// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: myserver.proto

package myserver

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MyServer service

type MyServerService interface {
	// 用户上线a
	ConnectA(ctx context.Context, in *ConnectReq, opts ...client.CallOption) (*ConnectRsp, error)
	// 用户断线
	Disconnect(ctx context.Context, in *DisconnectReq, opts ...client.CallOption) (*DisconnectRsp, error)
	// 推送消息
	Message(ctx context.Context, in *MessageReq, opts ...client.CallOption) (*MessageRsp, error)
}

type myServerService struct {
	c    client.Client
	name string
}

func NewMyServerService(name string, c client.Client) MyServerService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "myserver"
	}
	return &myServerService{
		c:    c,
		name: name,
	}
}

func (c *myServerService) ConnectA(ctx context.Context, in *ConnectReq, opts ...client.CallOption) (*ConnectRsp, error) {
	req := c.c.NewRequest(c.name, "MyServer.ConnectA", in)
	out := new(ConnectRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServerService) Disconnect(ctx context.Context, in *DisconnectReq, opts ...client.CallOption) (*DisconnectRsp, error) {
	req := c.c.NewRequest(c.name, "MyServer.Disconnect", in)
	out := new(DisconnectRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServerService) Message(ctx context.Context, in *MessageReq, opts ...client.CallOption) (*MessageRsp, error) {
	req := c.c.NewRequest(c.name, "MyServer.Message", in)
	out := new(MessageRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MyServer service

type MyServerHandler interface {
	// 用户上线a
	ConnectA(context.Context, *ConnectReq, *ConnectRsp) error
	// 用户断线
	Disconnect(context.Context, *DisconnectReq, *DisconnectRsp) error
	// 推送消息
	Message(context.Context, *MessageReq, *MessageRsp) error
}

func RegisterMyServerHandler(s server.Server, hdlr MyServerHandler, opts ...server.HandlerOption) error {
	type myServer interface {
		ConnectA(ctx context.Context, in *ConnectReq, out *ConnectRsp) error
		Disconnect(ctx context.Context, in *DisconnectReq, out *DisconnectRsp) error
		Message(ctx context.Context, in *MessageReq, out *MessageRsp) error
	}
	type MyServer struct {
		myServer
	}
	h := &myServerHandler{hdlr}
	return s.Handle(s.NewHandler(&MyServer{h}, opts...))
}

type myServerHandler struct {
	MyServerHandler
}

func (h *myServerHandler) ConnectA(ctx context.Context, in *ConnectReq, out *ConnectRsp) error {
	return h.MyServerHandler.ConnectA(ctx, in, out)
}

func (h *myServerHandler) Disconnect(ctx context.Context, in *DisconnectReq, out *DisconnectRsp) error {
	return h.MyServerHandler.Disconnect(ctx, in, out)
}

func (h *myServerHandler) Message(ctx context.Context, in *MessageReq, out *MessageRsp) error {
	return h.MyServerHandler.Message(ctx, in, out)
}
