// Code generated by protoc-gen-go. DO NOT EDIT.
// source: myserver.proto

package myserver

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConnectReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	WsId                 string   `protobuf:"bytes,2,opt,name=WsId,proto3" json:"WsId,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=Service,proto3" json:"Service,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectReq) Reset()         { *m = ConnectReq{} }
func (m *ConnectReq) String() string { return proto.CompactTextString(m) }
func (*ConnectReq) ProtoMessage()    {}
func (*ConnectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ad3568a2d802a3, []int{0}
}

func (m *ConnectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectReq.Unmarshal(m, b)
}
func (m *ConnectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectReq.Marshal(b, m, deterministic)
}
func (m *ConnectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectReq.Merge(m, src)
}
func (m *ConnectReq) XXX_Size() int {
	return xxx_messageInfo_ConnectReq.Size(m)
}
func (m *ConnectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectReq proto.InternalMessageInfo

func (m *ConnectReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ConnectReq) GetWsId() string {
	if m != nil {
		return m.WsId
	}
	return ""
}

func (m *ConnectReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ConnectReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ConnectRsp struct {
	Confirm              bool     `protobuf:"varint,1,opt,name=confirm,proto3" json:"confirm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRsp) Reset()         { *m = ConnectRsp{} }
func (m *ConnectRsp) String() string { return proto.CompactTextString(m) }
func (*ConnectRsp) ProtoMessage()    {}
func (*ConnectRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ad3568a2d802a3, []int{1}
}

func (m *ConnectRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRsp.Unmarshal(m, b)
}
func (m *ConnectRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRsp.Marshal(b, m, deterministic)
}
func (m *ConnectRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRsp.Merge(m, src)
}
func (m *ConnectRsp) XXX_Size() int {
	return xxx_messageInfo_ConnectRsp.Size(m)
}
func (m *ConnectRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRsp proto.InternalMessageInfo

func (m *ConnectRsp) GetConfirm() bool {
	if m != nil {
		return m.Confirm
	}
	return false
}

type DisconnectReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	WsId                 string   `protobuf:"bytes,2,opt,name=WsId,proto3" json:"WsId,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=Service,proto3" json:"Service,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectReq) Reset()         { *m = DisconnectReq{} }
func (m *DisconnectReq) String() string { return proto.CompactTextString(m) }
func (*DisconnectReq) ProtoMessage()    {}
func (*DisconnectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ad3568a2d802a3, []int{2}
}

func (m *DisconnectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectReq.Unmarshal(m, b)
}
func (m *DisconnectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectReq.Marshal(b, m, deterministic)
}
func (m *DisconnectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectReq.Merge(m, src)
}
func (m *DisconnectReq) XXX_Size() int {
	return xxx_messageInfo_DisconnectReq.Size(m)
}
func (m *DisconnectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectReq.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectReq proto.InternalMessageInfo

func (m *DisconnectReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DisconnectReq) GetWsId() string {
	if m != nil {
		return m.WsId
	}
	return ""
}

func (m *DisconnectReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *DisconnectReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DisconnectRsp struct {
	Confirm              bool     `protobuf:"varint,1,opt,name=confirm,proto3" json:"confirm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRsp) Reset()         { *m = DisconnectRsp{} }
func (m *DisconnectRsp) String() string { return proto.CompactTextString(m) }
func (*DisconnectRsp) ProtoMessage()    {}
func (*DisconnectRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ad3568a2d802a3, []int{3}
}

func (m *DisconnectRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRsp.Unmarshal(m, b)
}
func (m *DisconnectRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRsp.Marshal(b, m, deterministic)
}
func (m *DisconnectRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRsp.Merge(m, src)
}
func (m *DisconnectRsp) XXX_Size() int {
	return xxx_messageInfo_DisconnectRsp.Size(m)
}
func (m *DisconnectRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRsp proto.InternalMessageInfo

func (m *DisconnectRsp) GetConfirm() bool {
	if m != nil {
		return m.Confirm
	}
	return false
}

type MessageReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	WsId                 string   `protobuf:"bytes,2,opt,name=WsId,proto3" json:"WsId,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=Service,proto3" json:"Service,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReq) Reset()         { *m = MessageReq{} }
func (m *MessageReq) String() string { return proto.CompactTextString(m) }
func (*MessageReq) ProtoMessage()    {}
func (*MessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ad3568a2d802a3, []int{4}
}

func (m *MessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReq.Unmarshal(m, b)
}
func (m *MessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReq.Marshal(b, m, deterministic)
}
func (m *MessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReq.Merge(m, src)
}
func (m *MessageReq) XXX_Size() int {
	return xxx_messageInfo_MessageReq.Size(m)
}
func (m *MessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReq proto.InternalMessageInfo

func (m *MessageReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MessageReq) GetWsId() string {
	if m != nil {
		return m.WsId
	}
	return ""
}

func (m *MessageReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *MessageReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type MessageRsp struct {
	Confirm              bool     `protobuf:"varint,1,opt,name=confirm,proto3" json:"confirm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRsp) Reset()         { *m = MessageRsp{} }
func (m *MessageRsp) String() string { return proto.CompactTextString(m) }
func (*MessageRsp) ProtoMessage()    {}
func (*MessageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_64ad3568a2d802a3, []int{5}
}

func (m *MessageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRsp.Unmarshal(m, b)
}
func (m *MessageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRsp.Marshal(b, m, deterministic)
}
func (m *MessageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRsp.Merge(m, src)
}
func (m *MessageRsp) XXX_Size() int {
	return xxx_messageInfo_MessageRsp.Size(m)
}
func (m *MessageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRsp proto.InternalMessageInfo

func (m *MessageRsp) GetConfirm() bool {
	if m != nil {
		return m.Confirm
	}
	return false
}

func init() {
	proto.RegisterType((*ConnectReq)(nil), "myserver.ConnectReq")
	proto.RegisterType((*ConnectRsp)(nil), "myserver.ConnectRsp")
	proto.RegisterType((*DisconnectReq)(nil), "myserver.DisconnectReq")
	proto.RegisterType((*DisconnectRsp)(nil), "myserver.DisconnectRsp")
	proto.RegisterType((*MessageReq)(nil), "myserver.MessageReq")
	proto.RegisterType((*MessageRsp)(nil), "myserver.MessageRsp")
}

func init() { proto.RegisterFile("myserver.proto", fileDescriptor_64ad3568a2d802a3) }

var fileDescriptor_64ad3568a2d802a3 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xad, 0x2c, 0x4e,
	0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x32,
	0xb8, 0xb8, 0x9c, 0xf3, 0xf3, 0xf2, 0x52, 0x93, 0x4b, 0x82, 0x52, 0x0b, 0x85, 0xc4, 0xb8, 0xd8,
	0x42, 0x8b, 0x53, 0x8b, 0x3c, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0xa0, 0x3c, 0x21,
	0x21, 0x2e, 0x96, 0xf0, 0x62, 0xcf, 0x14, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b,
	0x48, 0x82, 0x8b, 0x3d, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x82, 0x19, 0x2c, 0x0c, 0xe3,
	0x0a, 0x89, 0x70, 0xb1, 0x86, 0xe4, 0x67, 0xa7, 0xe6, 0x49, 0xb0, 0x80, 0xc5, 0x21, 0x1c, 0x25,
	0x35, 0x84, 0x4d, 0xc5, 0x05, 0x20, 0xdd, 0xc9, 0xf9, 0x79, 0x69, 0x99, 0x45, 0xb9, 0x60, 0xab,
	0x38, 0x82, 0x60, 0x5c, 0xa5, 0x6c, 0x2e, 0x5e, 0x97, 0xcc, 0xe2, 0x64, 0xfa, 0x38, 0x4a, 0x13,
	0xc5, 0x32, 0xbc, 0xee, 0xca, 0xe0, 0xe2, 0xf2, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xa5, 0x43,
	0x48, 0xc1, 0x6c, 0xc2, 0xe7, 0x22, 0xa3, 0xfd, 0x8c, 0x5c, 0x1c, 0xbe, 0x95, 0xc1, 0xe0, 0x88,
	0x14, 0xb2, 0xe0, 0xe2, 0x80, 0x06, 0xaf, 0xa3, 0x90, 0x88, 0x1e, 0x3c, 0xbe, 0x11, 0x91, 0x2b,
	0x85, 0x45, 0xb4, 0xb8, 0x40, 0x89, 0x41, 0xc8, 0x81, 0x8b, 0x0b, 0x11, 0x06, 0x42, 0xe2, 0x08,
	0x55, 0x28, 0xd1, 0x20, 0x85, 0x5d, 0x02, 0x6c, 0x82, 0x39, 0x17, 0x3b, 0xd4, 0xc1, 0xc8, 0x56,
	0x23, 0x42, 0x4b, 0x0a, 0x8b, 0x28, 0x48, 0xa3, 0x93, 0x40, 0x14, 0x1f, 0x38, 0x41, 0xea, 0xc3,
	0xa4, 0x93, 0xd8, 0xc0, 0x7c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0xfb, 0xb0, 0xb6,
	0xb2, 0x02, 0x00, 0x00,
}
