// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gameprovide.proto

package gameprovide

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConnectReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	WsId                 string   `protobuf:"bytes,2,opt,name=WsId,proto3" json:"WsId,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=Service,proto3" json:"Service,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectReq) Reset()         { *m = ConnectReq{} }
func (m *ConnectReq) String() string { return proto.CompactTextString(m) }
func (*ConnectReq) ProtoMessage()    {}
func (*ConnectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dd55f6ea6329281, []int{0}
}

func (m *ConnectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectReq.Unmarshal(m, b)
}
func (m *ConnectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectReq.Marshal(b, m, deterministic)
}
func (m *ConnectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectReq.Merge(m, src)
}
func (m *ConnectReq) XXX_Size() int {
	return xxx_messageInfo_ConnectReq.Size(m)
}
func (m *ConnectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectReq proto.InternalMessageInfo

func (m *ConnectReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ConnectReq) GetWsId() string {
	if m != nil {
		return m.WsId
	}
	return ""
}

func (m *ConnectReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ConnectReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ConnectRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRsp) Reset()         { *m = ConnectRsp{} }
func (m *ConnectRsp) String() string { return proto.CompactTextString(m) }
func (*ConnectRsp) ProtoMessage()    {}
func (*ConnectRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dd55f6ea6329281, []int{1}
}

func (m *ConnectRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRsp.Unmarshal(m, b)
}
func (m *ConnectRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRsp.Marshal(b, m, deterministic)
}
func (m *ConnectRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRsp.Merge(m, src)
}
func (m *ConnectRsp) XXX_Size() int {
	return xxx_messageInfo_ConnectRsp.Size(m)
}
func (m *ConnectRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRsp proto.InternalMessageInfo

type DisconnectReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectReq) Reset()         { *m = DisconnectReq{} }
func (m *DisconnectReq) String() string { return proto.CompactTextString(m) }
func (*DisconnectReq) ProtoMessage()    {}
func (*DisconnectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dd55f6ea6329281, []int{2}
}

func (m *DisconnectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectReq.Unmarshal(m, b)
}
func (m *DisconnectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectReq.Marshal(b, m, deterministic)
}
func (m *DisconnectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectReq.Merge(m, src)
}
func (m *DisconnectReq) XXX_Size() int {
	return xxx_messageInfo_DisconnectReq.Size(m)
}
func (m *DisconnectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectReq.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectReq proto.InternalMessageInfo

func (m *DisconnectReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DisconnectReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DisconnectRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRsp) Reset()         { *m = DisconnectRsp{} }
func (m *DisconnectRsp) String() string { return proto.CompactTextString(m) }
func (*DisconnectRsp) ProtoMessage()    {}
func (*DisconnectRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dd55f6ea6329281, []int{3}
}

func (m *DisconnectRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRsp.Unmarshal(m, b)
}
func (m *DisconnectRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRsp.Marshal(b, m, deterministic)
}
func (m *DisconnectRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRsp.Merge(m, src)
}
func (m *DisconnectRsp) XXX_Size() int {
	return xxx_messageInfo_DisconnectRsp.Size(m)
}
func (m *DisconnectRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRsp proto.InternalMessageInfo

type MessageReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReq) Reset()         { *m = MessageReq{} }
func (m *MessageReq) String() string { return proto.CompactTextString(m) }
func (*MessageReq) ProtoMessage()    {}
func (*MessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dd55f6ea6329281, []int{4}
}

func (m *MessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReq.Unmarshal(m, b)
}
func (m *MessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReq.Marshal(b, m, deterministic)
}
func (m *MessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReq.Merge(m, src)
}
func (m *MessageReq) XXX_Size() int {
	return xxx_messageInfo_MessageReq.Size(m)
}
func (m *MessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReq proto.InternalMessageInfo

func (m *MessageReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MessageReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MessageReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type MessageRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRsp) Reset()         { *m = MessageRsp{} }
func (m *MessageRsp) String() string { return proto.CompactTextString(m) }
func (*MessageRsp) ProtoMessage()    {}
func (*MessageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dd55f6ea6329281, []int{5}
}

func (m *MessageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRsp.Unmarshal(m, b)
}
func (m *MessageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRsp.Marshal(b, m, deterministic)
}
func (m *MessageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRsp.Merge(m, src)
}
func (m *MessageRsp) XXX_Size() int {
	return xxx_messageInfo_MessageRsp.Size(m)
}
func (m *MessageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRsp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ConnectReq)(nil), "gameprovide.ConnectReq")
	proto.RegisterType((*ConnectRsp)(nil), "gameprovide.ConnectRsp")
	proto.RegisterType((*DisconnectReq)(nil), "gameprovide.DisconnectReq")
	proto.RegisterType((*DisconnectRsp)(nil), "gameprovide.DisconnectRsp")
	proto.RegisterType((*MessageReq)(nil), "gameprovide.MessageReq")
	proto.RegisterType((*MessageRsp)(nil), "gameprovide.MessageRsp")
}

func init() { proto.RegisterFile("gameprovide.proto", fileDescriptor_5dd55f6ea6329281) }

var fileDescriptor_5dd55f6ea6329281 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x35, 0x4d, 0x6d, 0xe8, 0x58, 0x91, 0x8e, 0xa2, 0x4b, 0x4e, 0x65, 0x4f, 0x3d, 0x55, 0xd0,
	0x73, 0x2e, 0x5a, 0x84, 0x1e, 0xf4, 0x10, 0x95, 0x82, 0xb7, 0x34, 0x19, 0x6a, 0x28, 0x66, 0xd7,
	0x4c, 0xe8, 0x7f, 0xfa, 0x47, 0xe2, 0x98, 0xba, 0x49, 0xa9, 0xe4, 0xb6, 0xf3, 0x66, 0xe6, 0xbd,
	0x37, 0x8f, 0x85, 0xf1, 0x3a, 0xf9, 0x20, 0x5b, 0x9a, 0x6d, 0x9e, 0xd1, 0xcc, 0x96, 0xa6, 0x32,
	0x78, 0xd2, 0x80, 0xf4, 0x3b, 0xc0, 0xbd, 0x29, 0x0a, 0x4a, 0xab, 0x98, 0x3e, 0xf1, 0x12, 0x06,
	0xaf, 0x4c, 0xe5, 0x22, 0x53, 0xde, 0xc4, 0x9b, 0xfa, 0x71, 0x5d, 0x21, 0x42, 0x7f, 0xc9, 0x8b,
	0x4c, 0xf5, 0x26, 0xde, 0x74, 0x18, 0xcb, 0x1b, 0x15, 0x04, 0xcf, 0x54, 0x6e, 0xf3, 0x94, 0x94,
	0x2f, 0xf0, 0xae, 0xc4, 0x0b, 0x38, 0x7e, 0x31, 0x1b, 0x2a, 0x54, 0x5f, 0xf0, 0xdf, 0x42, 0x8f,
	0x9c, 0x12, 0x5b, 0x1d, 0xc1, 0xe9, 0x3c, 0xe7, 0xb4, 0x5b, 0xfa, 0x8f, 0xac, 0xd7, 0x24, 0x3b,
	0x6b, 0xad, 0xb3, 0xd5, 0x4f, 0x00, 0x8f, 0xc4, 0x9c, 0xac, 0xa9, 0xe3, 0x8e, 0x79, 0x52, 0x25,
	0xc2, 0x35, 0x8a, 0xe5, 0xed, 0x04, 0xfc, 0x3d, 0xb7, 0x3b, 0x3e, 0xb6, 0x37, 0x5f, 0x1e, 0x0c,
	0x97, 0xb4, 0x62, 0x93, 0x6e, 0xa8, 0xc2, 0x08, 0x82, 0xfa, 0x12, 0xbc, 0x9a, 0x35, 0xf3, 0x75,
	0x49, 0x86, 0x87, 0x1b, 0x6c, 0xf5, 0x11, 0x3e, 0x00, 0x38, 0xef, 0x18, 0xb6, 0x06, 0x5b, 0x99,
	0x84, 0xff, 0xf6, 0x84, 0x27, 0x82, 0xa0, 0xb6, 0xb8, 0x67, 0xc3, 0x05, 0x11, 0x1e, 0x6e, 0xfc,
	0xac, 0xdf, 0x9d, 0xbf, 0x8d, 0xe5, 0x3f, 0x5c, 0x37, 0x26, 0x56, 0x03, 0x81, 0x6e, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xc7, 0x92, 0x88, 0xdc, 0x37, 0x02, 0x00, 0x00,
}
