// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConnectReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	WsId                 string   `protobuf:"bytes,2,opt,name=WsId,proto3" json:"WsId,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=Service,proto3" json:"Service,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectReq) Reset()         { *m = ConnectReq{} }
func (m *ConnectReq) String() string { return proto.CompactTextString(m) }
func (*ConnectReq) ProtoMessage()    {}
func (*ConnectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *ConnectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectReq.Unmarshal(m, b)
}
func (m *ConnectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectReq.Marshal(b, m, deterministic)
}
func (m *ConnectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectReq.Merge(m, src)
}
func (m *ConnectReq) XXX_Size() int {
	return xxx_messageInfo_ConnectReq.Size(m)
}
func (m *ConnectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectReq proto.InternalMessageInfo

func (m *ConnectReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ConnectReq) GetWsId() string {
	if m != nil {
		return m.WsId
	}
	return ""
}

func (m *ConnectReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ConnectReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ConnectRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRsp) Reset()         { *m = ConnectRsp{} }
func (m *ConnectRsp) String() string { return proto.CompactTextString(m) }
func (*ConnectRsp) ProtoMessage()    {}
func (*ConnectRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *ConnectRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRsp.Unmarshal(m, b)
}
func (m *ConnectRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRsp.Marshal(b, m, deterministic)
}
func (m *ConnectRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRsp.Merge(m, src)
}
func (m *ConnectRsp) XXX_Size() int {
	return xxx_messageInfo_ConnectRsp.Size(m)
}
func (m *ConnectRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRsp proto.InternalMessageInfo

type DisconnectReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectReq) Reset()         { *m = DisconnectReq{} }
func (m *DisconnectReq) String() string { return proto.CompactTextString(m) }
func (*DisconnectReq) ProtoMessage()    {}
func (*DisconnectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *DisconnectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectReq.Unmarshal(m, b)
}
func (m *DisconnectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectReq.Marshal(b, m, deterministic)
}
func (m *DisconnectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectReq.Merge(m, src)
}
func (m *DisconnectReq) XXX_Size() int {
	return xxx_messageInfo_DisconnectReq.Size(m)
}
func (m *DisconnectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectReq.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectReq proto.InternalMessageInfo

func (m *DisconnectReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DisconnectReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DisconnectRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRsp) Reset()         { *m = DisconnectRsp{} }
func (m *DisconnectRsp) String() string { return proto.CompactTextString(m) }
func (*DisconnectRsp) ProtoMessage()    {}
func (*DisconnectRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *DisconnectRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRsp.Unmarshal(m, b)
}
func (m *DisconnectRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRsp.Marshal(b, m, deterministic)
}
func (m *DisconnectRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRsp.Merge(m, src)
}
func (m *DisconnectRsp) XXX_Size() int {
	return xxx_messageInfo_DisconnectRsp.Size(m)
}
func (m *DisconnectRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRsp proto.InternalMessageInfo

type MessageReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReq) Reset()         { *m = MessageReq{} }
func (m *MessageReq) String() string { return proto.CompactTextString(m) }
func (*MessageReq) ProtoMessage()    {}
func (*MessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *MessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReq.Unmarshal(m, b)
}
func (m *MessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReq.Marshal(b, m, deterministic)
}
func (m *MessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReq.Merge(m, src)
}
func (m *MessageReq) XXX_Size() int {
	return xxx_messageInfo_MessageReq.Size(m)
}
func (m *MessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReq proto.InternalMessageInfo

func (m *MessageReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MessageReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MessageReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type MessageRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRsp) Reset()         { *m = MessageRsp{} }
func (m *MessageRsp) String() string { return proto.CompactTextString(m) }
func (*MessageRsp) ProtoMessage()    {}
func (*MessageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5}
}

func (m *MessageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRsp.Unmarshal(m, b)
}
func (m *MessageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRsp.Marshal(b, m, deterministic)
}
func (m *MessageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRsp.Merge(m, src)
}
func (m *MessageRsp) XXX_Size() int {
	return xxx_messageInfo_MessageRsp.Size(m)
}
func (m *MessageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRsp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ConnectReq)(nil), "message.ConnectReq")
	proto.RegisterType((*ConnectRsp)(nil), "message.ConnectRsp")
	proto.RegisterType((*DisconnectReq)(nil), "message.DisconnectReq")
	proto.RegisterType((*DisconnectRsp)(nil), "message.DisconnectRsp")
	proto.RegisterType((*MessageReq)(nil), "message.MessageReq")
	proto.RegisterType((*MessageRsp)(nil), "message.MessageRsp")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xb5, 0x14, 0x69, 0x78, 0xc1, 0x98, 0x8c, 0x86, 0x6c, 0x7a, 0x22, 0x7b, 0xe2, 0xd4, 0x83,
	0x86, 0xa3, 0x5e, 0xe4, 0xc2, 0x41, 0x0f, 0x55, 0xc3, 0xb9, 0x94, 0x09, 0x12, 0x42, 0x77, 0xed,
	0x34, 0xfe, 0x37, 0xff, 0x9d, 0x71, 0x59, 0x58, 0x10, 0x93, 0xde, 0x66, 0x5e, 0x76, 0xde, 0xd7,
	0x02, 0xab, 0x62, 0xcb, 0x99, 0xad, 0x4d, 0x63, 0x28, 0xd9, 0xb2, 0x48, 0xb1, 0x62, 0xfd, 0x01,
	0x3c, 0x99, 0xaa, 0xe2, 0xb2, 0xc9, 0xf9, 0x93, 0x86, 0xe8, 0xbd, 0x0b, 0xd7, 0xb3, 0xa5, 0x8a,
	0x46, 0xd1, 0x38, 0xce, 0xfd, 0x46, 0x84, 0xee, 0x5c, 0x66, 0x4b, 0xd5, 0x19, 0x45, 0xe3, 0x7e,
	0xee, 0x66, 0x52, 0x48, 0x5e, 0xb9, 0xfe, 0x5a, 0x97, 0xac, 0x62, 0x07, 0xef, 0x57, 0xba, 0xc5,
	0xe5, 0x9b, 0xd9, 0x70, 0xa5, 0xba, 0x0e, 0xdf, 0x2d, 0x7a, 0x10, 0x94, 0xc4, 0xea, 0x07, 0x5c,
	0x4d, 0xd7, 0x52, 0xb6, 0x4b, 0x1f, 0xc8, 0x3a, 0xc7, 0x64, 0xd7, 0x27, 0xe7, 0x62, 0xf5, 0x0b,
	0xf0, 0xbc, 0x8b, 0xd4, 0x92, 0x63, 0x5a, 0x34, 0x85, 0xe3, 0x1a, 0xe4, 0x6e, 0x0e, 0x02, 0xf1,
	0x1f, 0xb7, 0x7b, 0x3e, 0xb1, 0x77, 0xdf, 0x11, 0xfa, 0x73, 0x5e, 0x88, 0x29, 0x37, 0xdc, 0xd0,
	0x04, 0x89, 0x4f, 0x42, 0x37, 0x99, 0x2f, 0x32, 0x0b, 0x2d, 0xa6, 0xe7, 0xa0, 0x58, 0x7d, 0x41,
	0x8f, 0x40, 0xf0, 0x4c, 0xc3, 0xc3, 0xa3, 0x93, 0x1e, 0xd2, 0x7f, 0x71, 0x77, 0x3f, 0x41, 0xe2,
	0x2d, 0x1d, 0xc9, 0x86, 0xd0, 0xe9, 0x39, 0xf8, 0x7b, 0xb6, 0xe8, 0xb9, 0x1f, 0xbf, 0xff, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x6d, 0xbf, 0xa0, 0x59, 0xff, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WebsocketClient is the client API for Websocket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebsocketClient interface {
	// 用户上线
	Connect(ctx context.Context, in *ConnectReq, opts ...grpc.CallOption) (*ConnectRsp, error)
	// 用户断线
	Disconnect(ctx context.Context, in *DisconnectReq, opts ...grpc.CallOption) (*DisconnectRsp, error)
	// 推送消息
	Message(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*MessageRsp, error)
}

type websocketClient struct {
	cc *grpc.ClientConn
}

func NewWebsocketClient(cc *grpc.ClientConn) WebsocketClient {
	return &websocketClient{cc}
}

func (c *websocketClient) Connect(ctx context.Context, in *ConnectReq, opts ...grpc.CallOption) (*ConnectRsp, error) {
	out := new(ConnectRsp)
	err := c.cc.Invoke(ctx, "/message.Websocket/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websocketClient) Disconnect(ctx context.Context, in *DisconnectReq, opts ...grpc.CallOption) (*DisconnectRsp, error) {
	out := new(DisconnectRsp)
	err := c.cc.Invoke(ctx, "/message.Websocket/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websocketClient) Message(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*MessageRsp, error) {
	out := new(MessageRsp)
	err := c.cc.Invoke(ctx, "/message.Websocket/Message", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebsocketServer is the server API for Websocket service.
type WebsocketServer interface {
	// 用户上线
	Connect(context.Context, *ConnectReq) (*ConnectRsp, error)
	// 用户断线
	Disconnect(context.Context, *DisconnectReq) (*DisconnectRsp, error)
	// 推送消息
	Message(context.Context, *MessageReq) (*MessageRsp, error)
}

// UnimplementedWebsocketServer can be embedded to have forward compatible implementations.
type UnimplementedWebsocketServer struct {
}

func (*UnimplementedWebsocketServer) Connect(ctx context.Context, req *ConnectReq) (*ConnectRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (*UnimplementedWebsocketServer) Disconnect(ctx context.Context, req *DisconnectReq) (*DisconnectRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (*UnimplementedWebsocketServer) Message(ctx context.Context, req *MessageReq) (*MessageRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Message not implemented")
}

func RegisterWebsocketServer(s *grpc.Server, srv WebsocketServer) {
	s.RegisterService(&_Websocket_serviceDesc, srv)
}

func _Websocket_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsocketServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Websocket/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsocketServer).Connect(ctx, req.(*ConnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Websocket_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsocketServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Websocket/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsocketServer).Disconnect(ctx, req.(*DisconnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Websocket_Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsocketServer).Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Websocket/Message",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsocketServer).Message(ctx, req.(*MessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Websocket_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.Websocket",
	HandlerType: (*WebsocketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Websocket_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Websocket_Disconnect_Handler,
		},
		{
			MethodName: "Message",
			Handler:    _Websocket_Message_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
